### ISSUE TITLE
Can't backspace in textbox if too much text

### ISSUE THREAD

**Issue by pdesaulniers** [zynaddsubfx/zyn-fusion-issues#174] opened 2018-07-13 19:05 UTC
I've been able to reproduce this issue using latest zyn built with `build-linux.rb`, in both the Macro Learn slot names and preset names textboxes.

If I type a huge name, I become unable to erase it using backspace: 
![2018-07-13-15 00 30](https://user-images.githubusercontent.com/23723605/42709145-8ad4e790-86ad-11e8-8ec4-31c5effb97bf.png)

The search bar in the presets browser seems unaffected.

**Comment by pdesaulniers** [comment] 2018-07-13 19:19
Actually, it doesn't have to be bigger than the textbox. I can't backspace starting from about here (note the cursor position):
![2018-07-13-15 17 34](https://user-images.githubusercontent.com/23723605/42709862-e43a4cd8-86af-11e8-86f7-d74e7c3bad03.png)

**Comment by fundamental** [comment] 2018-07-14 00:24
This is one of the dumb-ist bugs that I've been battling for ages with mruby.
What's basically happening:

```
# ruby code
label = "some string"
puts label # writes 'some string'
label = label[0...-1]
puts label # writes 'some strin'
some_c_method(label)

//C code
{
   printf("%s\n", label_parameter);//prints 'some string'
  //!!!!! how did the 'g' get back on the end of the string
  //after I deleted it and confirmed that I deleted it??!!!
}
```

I've had a few dirty workarounds in place elsewhere as this is the only known bug that I've been dealing with in regards to the particular git revision of mruby that's been being used internally and that seemed easier than updating. Now time to squash the new occurrences of this weird glitch.

**Comment by fundamental** [comment] 2018-07-14 02:39
Ok, I can confirm there are regressions with the current version of mruby and I've filed a few issues upstream including https://github.com/mruby/mruby/issues/4070 and https://github.com/mruby/mruby/issues/4069 . Once those issues are resolved I'll take another stab at updating the mruby version which will hopefully resolve this issue.

**Comment by fundamental** [comment] 2018-07-28 16:19
Ok, those two upstream issues are more or less resolved, so I took another stab at updating the mruby version. Unfortunately that has resulted in me finding a new bug which seems to be memory layout and workload dependent (i.e. a huge pain to debug). Heck while trying to run git bisect I got stuck in a merged git-subtree and I didn't even know that was a possible state for bisect to get to.

I'd consider this issue paused until https://github.com/mruby/mruby/issues/4073 has some resolution.

**Comment by pgervais** [comment] 2023-05-01 12:11
@fundamental It looks like the original issue that motivated this ticket is still there, the mruby issue you mention in the above comment has been resolved, and I checked the mruby version used by mruby-zest-master contains the "fix".

I personally don't want to get into the gust of mruby but I would be happy to implement a workaround to get rid of the issue in zest. How does that sound?

**Comment by fundamental** [comment] 2023-05-01 23:38
Resolved via https://github.com/mruby-zest/mruby-zest-build/commit/a5810360f86ef7bc18825ec0f2271eb9797e9ae1

**Closed as completed by fundamental** 2023-05-01 23:38 UTC
Labels: bug, confirmed

**Comment by pgervais** [comment] 2023-05-02 07:04
Thanks!
