### ISSUE TITLE
Subsynth Formant fiter parameters - missing labels and appear not to work

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#356] opened 2022-04-22 16:58 UTC
Struggling with formant filter.
Under addsynth settings work,
Under subsynth most settings do nothing and some are missing labels.

I wish I could find a decent explanation of how formant filter is supposed to work!

**Comment by fundamental** [comment] 2022-04-26 21:37
Looking at the UI it seems to me that all the labels are there, as per settings doing nothing, the formant filter is a weird one. I totally agree an underdocumented one as well. So, you have a set of vowels and a sequence that runs through the vowels. Each vowel is composed out of a set of formants. Each formant is a frequency, bandwidth, and amplitude combination. Moving between vowels involves blending the formants from one vowel to the next and the vowels are sequenced using the sequencer subsection.

It ends up being wristwatch logic to understand what's happening unfortunately.

https://github.com/zynaddsubfx/zyn-fusion-issues/issues/98 details some discussion on how it might be modified to make the process much more visually obvious, though even if those changes were implemented, there's plenty more UX issues to explore to make it easy to have more musical utility out of the filter, since it is an interesting part of zyn.

**Comment by zynmuse** [comment] 2022-04-27 10:09
Hi
The labels which are present in the ADDsynth formant filter are not present in the SUBsynth formant filter.
The missing labels are  "Slew", "Cutoff", "Clarity"  and "Octave".
![Screenshot_2022-04-27_11-03-34](https://user-images.githubusercontent.com/63783478/165494859-506278f1-189b-446d-a43f-d4c67137fc35.jpg)

I'll play again with functionality. But my impression was that the formant filter parameters could not be changed here, although it did work in the addsynth.

**Comment by fundamental** [comment] 2022-05-04 21:23
I've confirmed the bug exists in subsynth. Looking at the debug output I see lines like:
```
[WARNING:osc-bridge] Invalid Handle "/part0/kit0/subpars/AmpEnvelope/vowel_seq0"
```

It should be a relatively easy fix.

**Comment by fundamental** [comment] 2022-05-07 16:32
The original bug has been resolved via https://github.com/mruby-zest/mruby-zest-build/commit/edaedb64282fa01527eed4bceb1ad0efa3b05838

**Comment by zynmuse** [comment] 2022-05-12 16:35
Many thanks!

**Comment by pgervais** [comment] 2023-04-17 16:13
I just checked that the initial issue has been resolved.

**Closed as completed by pgervais** 2023-04-17 16:13 UTC
Labels: bug, help wanted, question, confirmed
