### ISSUE TITLE
Pan controls are inverted

### ISSUE THREAD

**Issue by VincyZed** [zynaddsubfx/zyn-fusion-issues#376] opened 2022-12-10 19:34 UTC
The pan controls in Zyn-Fusion are inverted. Dragging the knob to the left actually pans the audio to the right, and vice-versa.
The value of 0 still applies a random value correctly, though.

**Comment by fundamental** [comment] 2022-12-10 23:25
There's a global left/right invert setting which may be related.

**Comment by VincyZed** [comment] 2022-12-11 00:40
Just found that button. It was off, and turning it on or off makes no difference.

**Comment by pgervais** [comment] 2023-03-12 18:08
I confirm that toggling the "Swap stereo" switch does nothing with zynfusion / zynaddsubfx git head as of last week.

**Comment by pgervais** [comment] 2023-04-06 08:48
The same issue exists with the fltk interface: channels are swapped and the global invert setting has no effect. So it's not an issue with the new UI.

**Comment by polluxsynth** [comment] 2023-04-22 05:33
Exactly which pan controls are we talking about here: the ones in the Mixer pane, in the Part settings, or somewhere else? Which environment (standalone, as a plugin (in which host?), etc)?

When I tested a few random patches just now both running in standalone mode on a PC or in Zynthian, the Mixer and Part pan controls appear to visually pan the audio in the correct direction as viewed on the VU meters in the Mixer pane as well as the global VU meter in the upper right hand corner of the UI, and the sound also audibly pans in the correct direction. (In these cases, I was operating in multi mode (starting zynaddsubfx with -O jack-multi, which is perhaps not the most common way).

(A while ago (January 2022) I fixed an issue in multi mode where the output from the individual parts was swapped due to a number of swaps internally, even though the sum output was correct. (https://github.com/zynaddsubfx/zyn-fusion-issues/issues/330)).

**Comment by pgervais** [comment] 2023-04-28 08:00
Thanks for keeping me honest. I went through all the pan controls I could find in the Zest standalone interface, on Linux.

- The general stereo swap switch indeed works (also on Mac/FLTK)  **as long as Zynadd is restarted**. This is mentioned in the FLTK UI, not in Zest.

- I checked that my physical cabling was set up correctly using Ardour, which I assumed does the right thing, as in: channel 1 is left, 2 is right. In all cases mentioned below, Zest's viewmeter in the top-right corner agreed with the sound output in the speakers.

Command line used: `zynaddsubfx -I jack -O jack -U -P 1337` + Zest launched using `make run` from the mruby-zest-build git directory.

With the 'swap stereo' setting unchecked, I found inverted panning in quite a few places

- Part settings > Instrument settings > Pan: correct. 0 is fully left.
- Mixer > 1 > Pan: correct. 0 is fully left.
- Add > Global > General > Pan: inverted. 0 is random.
- Add > Voice list > 1 > Panning: inverted. 0 is random.
- Sub > Global > General > Panning: inverted. 0 is random.
- Pad > Envelopes & LFOs > General > Panning: inverted. 0 is random.

I also looked at effects. For all effects that have a 'pan' button, the panning is handled correctly, with the exception of "distortion" for which the pan button appeared to have no effect.

**Comment by polluxsynth** [comment] 2023-05-01 06:28
Thanks @pgervais for the detailed list. I haven't checked the effects, but I can verify that all the other pan locations behave as you mention.

Where you planning to look into this as you are noted as the assignee of the issue?

**Comment by pgervais** [comment] 2023-05-01 06:50
My initial intention was to check whether this issue was fully resolved and I assigned the ticket to myself as a way to bookmark it. So if you want to take care of the fix, feel free to reassign the ticket to yourself. And if alternatively you would like some help, just let me know.

**Comment by polluxsynth** [comment] 2023-05-01 19:18
I'll see if I can have a look at it. Since I fixed a couple of pan issues already I'm a bit annoyed with myself for missing the ones that remain.

**Comment by polluxsynth** [comment] 2023-05-01 21:15
Seems I'm not registered as a collaborator, so I can't reassign the issue. @fundamental, would that be possible?

**Comment by polluxsynth** [comment] 2023-05-02 22:05
Looked in the code and found the location of all the Add/Sub/Pad pan bugs (should be an easy fix), but the pan in the distortion effect looked fine. After some more experimentation, it turns out that the L-R-Crossover (L.RC) control affects pan, so that if LRC is in its center position, pan essentially has no effect, since both L and R affect both channels equally. With LRC in its leftmost position, pan works as expected (and is inverted when LRC is in its rightmost position, as then L feeds R and R feeds L). I haven't dwelled to much on it, but instinctively it seems as if it's working as intended, even if it may not be completely intuitive depending on what you are expecting.

**Comment by polluxsynth** [comment] 2023-05-05 22:03
I've created a pull request if anyone wants to test: https://github.com/zynaddsubfx/zynaddsubfx/pull/242 .

**Comment by pgervais** [comment] 2023-06-10 13:51
Closing the ticket since the PR mentioned above has been merged. Thanks @polluxsynth !

**Closed as completed** 2023-06-10 13:52 UTC
Labels: bug
