### ISSUE TITLE
ADDsynth > VCE > Frequency > Coarse changes the way pitch envelope works

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#95] opened 2017-04-27 09:15 UTC
Try this (playing a note along to hear the changes as they happen)

1. Add a fast pitch envelope to make a sine wave go from high to low frequency quickly.
2. Touch the ADDsynth's vocie Coarse detune knob (make it non-zero) - the pitch envelope will radically change.
3. Use octave shift control - the sound will come back to how it was before you touched Coarse detune.

**Comment by pdesaulniers** [comment] 2018-12-22 00:23
Can't reproduce anymore, so I'm closing this.

**Closed as completed by pdesaulniers** 2018-12-22 00:23 UTC
Labels: bug, needs-testing
