### ISSUE TITLE
Random crash 

### ISSUE THREAD

**Issue by ctsexton** [zynaddsubfx/zyn-fusion-issues#218] opened 2019-04-20 02:41 UTC
Zyn crash dump. Just randomly exited while playing via midi keyboard. I wasn't touching the GUI.
```
trace:
	[0] /home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/mruby/mrblib/enum.rb:96:in Enumerable.each_with_index
	[1] /home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/mruby/mrblib/array.rb:17:in Array.each
	[2] /home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/mruby/mrblib/enum.rb:95:in Enumerable#each_with_index
	[3] /home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/fcache.rb:212:in Qml::Envelope.warp
	[4] /home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/fcache.rb:450:in Qml::Envelope.initialize
	[5] /home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:665:in ZRunner.tick_remote
/home/cts/.cache/aurman/zyn-fusion/src/mruby-zest-build/mruby/mrblib/enum.rb:96: undefined method '-' for nil (NoMethodError)
[FATAL ERROR] Mruby Is Unable To Continue
Deactivating and closing JACK client
```

**Comment by fundamental** [comment] 2019-04-20 02:55
Dupe of #196 which has a workaround in the most recent version.

**Closed as completed** 2021-08-15 02:45 UTC
