### ISSUE TITLE
Zyn randomly crashes when a base waveform changed 

### ISSUE THREAD

**Issue by allkhor** [zynaddsubfx/zyn-fusion-issues#164] opened 2018-05-18 17:40 UTC
No steps to reproduce this bug, because crash happens randomly.

```
trace:
	[0] zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:254:in ZRunner.handleCursorPos
	[1] zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:392:in ZRunner.handle_events
	[2] zyn-fusion-build/mruby-zest-build/mruby/mrblib/array.rb:17:in Array.each
	[3] zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:382:in ZRunner.handle_events
	[4] zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:663:in ZRunner.tick_events
zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/mrblib/script.rb:254: undefined method 'include?' for nil (NoMethodError)
[FATAL ERROR] Mruby Is Unable To Continue
```

**Comment by fundamental** [comment] 2018-05-20 16:42
On 05-18, Alexey wrote:
> No steps to reproduce this bug, because crash happens randomly.

Even if the bug does not have a 100% consistent way of replicating it,
is there a setquence of actions that you can do which eventually results
in the crash? (they may need to be repeated for instance to eventually
trigger the bug)

**Comment by pdesaulniers** [comment] 2018-07-16 05:06
I can reproduce this quite consistently by going through the spread type choices in Subsynth (ShiftU -> ShiftL -> PowerU -> Crash about 80% of the time)

**Comment by fundamental** [comment] 2018-07-17 02:42
Ok, this is an interesting one. It looks like the pre-requisites are:

1. a dropdown is produced that hangs over a Qml::HarmonicEdit
2. Within one frame a mouse click or release is observed for the dropdown and a move event occurs after the mouse press/release event
3. The Qml::HarmonicEdit doesn't have one internal structure fully initialized by a normal mouse press

While the error happens within Qml::HarmonicEdit::onMouseMove, that last layer is not shown in the stack trace that mruby displays (I'm hoping that after updating the mruby version it will be a bit better about that).

**Comment by fundamental** [comment] 2018-07-17 02:49
Fixed via https://github.com/mruby-zest/mruby-zest/commit/02812c8c956cffdfac4695bf1f6615e5967ff756

**Closed as completed by fundamental** 2018-07-17 02:49 UTC
